### ISSUE TITLE
Minecarts Become Stuck Mass Teleporting Between Frames

### ISSUE THREAD

**Issue by SkyeRangerDelta** [jusdino/BuildPortals#45]
Versioning:
BPortals version 2.2.0 running on MC 1.20.1 PaperMC build #71.

Environment:
Build 2 identical 2x1 no-corner style frames from emerald blocks. Use redstone blocks as activators. Once lightning strikes, lay powered rail in frame. Both portal frames have stone blocks behind them preventing wrong direction travel.

Bug:
Instead of traversing the portal normally - tested via walking through the portal - the minecart (both with and without player) will become lodged in a state of being in 'both portal frames' or at least teleporting very quickly between the two frames. The only way to stop the loop is to break the portal frame.

Considerations:
I have tried to use different rail configurations in the frames including alternating types between frames (normal vs. powered rail) and using inclined rails in the frames to 'push' the cart out. No solutions found this way.

Thank you for any support/fixes in advance.

![cartPortalBug](https://github.com/jusdino/BuildPortals/assets/12277949/1e305908-f257-485e-98cf-d375895c460f)
Edit; reconducted test with larger frame with no change in result. Added image.

**Comment by jusdino** [comment]
@SkyeRangerDelta thanks for the great details on this bug report! (and sorry I didn't look at this sooner). Working on a fix.

**Comment by jusdino** [comment]
@SkyeRangerDelta , can you confirm if this build fixes the issue for you?
https://github.com/jusdino/BuildPortals/suites/15058604103/artifacts/859899332

**Comment by SkyeRangerDelta** [comment]
> @SkyeRangerDelta , can you confirm if this build fixes the issue for you? https://github.com/jusdino/BuildPortals/suites/15058604103/artifacts/859899332

I can in fact confirm this build patched it. Looks like it works for both local / world teleports and for dimensional teleports too just fine. Thank you friend for the rather hasty fix.

Closing this for the sake of the fix identified/implemented.
